# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""Reads the captures and writes MEASUREMENTS.md.

The document is generated rather than written, so it says what the fixtures
hold today rather than what they held when someone last edited the prose.
"""

import collections
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TESTDATA = os.path.join(HERE, "testdata")
THREAD_KEYS = ("thread_id", "session_id", "conversation_id")


def load(case):
    """Every operation in a case, read back the way the receiver will read it."""
    import capture

    return list(capture.runs(os.path.join(TESTDATA, case)))


def metadata(fields):
    extra = (fields.get("extra") or ({}, 0))[0]
    return (extra.get("metadata") or {}) if isinstance(extra, dict) else {}


def thread_of(fields):
    md = metadata(fields)
    for key in THREAD_KEYS:
        if md.get(key):
            return str(md[key])
    return None


def table(rows, headers):
    out = ["| " + " | ".join(headers) + " |",
           "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(out)


def main():
    cases = sorted(d for d in os.listdir(TESTDATA)
                   if os.path.isdir(os.path.join(TESTDATA, d)))
    shape, totals = [], collections.Counter()
    bytes_by_type = collections.Counter()
    count_by_type = collections.Counter()
    for case in cases:
        ops = load(case)
        requests = len({id(m) for _, _, m, _ in ops})
        posts = sum(1 for op, _, _, _ in ops if op == "post")
        patches = sum(1 for op, _, _, _ in ops if op == "patch")
        open_runs = sum(1 for op, _, _, f in ops
                        if op == "post" and not f["_run"][0].get("end_time"))
        body = sum(m["body_bytes"] for m in
                   {id(m): m for _, _, m, _ in ops}.values())
        keys = sorted({thread_of(f) or "(none)" for _, _, _, f in ops})
        for op, _, _, fields in ops:
            run_type = fields["_run"][0].get("run_type", "?")
            count_by_type[run_type] += 1
            bytes_by_type[run_type] += sum(size for _, size in fields.values())
        shape.append((case, requests, len(ops), posts, patches, open_runs, body,
                      ", ".join("`%s`" % k for k in keys)[:60]))
        totals["ops"] += len(ops)
        totals["bytes"] += body

    everything = sum(bytes_by_type.values()) or 1
    by_type = [(t, count_by_type[t], bytes_by_type[t],
                "%.1f%%" % (100 * bytes_by_type[t] / everything))
               for t in sorted(bytes_by_type, key=lambda x: -bytes_by_type[x])]

    text = """<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->

# What the captures hold

Generated by `measure.py` from `testdata/`. Every number below is read from the
fixtures, so it changes when they are recaptured and never drifts from them.

## One row per case

`open` counts runs posted with no end time: work the client reported while it
was still running.

%s

## Where the bytes are

Counted across every case, by the kind of run that carried them.

%s

A graph's own `chain` runs carry the whole message list again in their inputs
and outputs, which is why they hold most of the bytes while saying nothing the
conversation does not already have.

## What each case is for

%s
""" % (
        table(shape, ["case", "requests", "runs", "post", "patch", "open", "bytes",
                      "thread keys"]),
        table(by_type, ["run type", "runs", "bytes", "share"]),
        table([(c, (getattr(__import__("agents"), "CASES")[c].__doc__ or "").strip()
                .splitlines()[0]) for c in cases if c in __import__("agents").CASES],
              ["case", "what it exercises"]),
    )
    with open(os.path.join(HERE, "MEASUREMENTS.md"), "w") as f:
        f.write(text)
    print("wrote MEASUREMENTS.md: %d cases, %d operations, %d bytes"
          % (len(cases), totals["ops"], totals["bytes"]))
    return 0


if __name__ == "__main__":
    sys.path.insert(0, HERE)
    sys.exit(main())
